--.........................................................................
--SQL script for post deployment configuration of load control
--Project: Dimensional MSSQL
--Layer: Cleanse
--.........................................................................
USE [{loadcontrol#loadcontrol#database_name}];
GO


--.........................................................................
--Prepare registration of load objects
--.........................................................................

EXEC [{loadcontrol#loadcontrol#schema_name}].[Build_LoadConfig] @LoadConfig = N'Dimensional MSSQL', @ModelObjectLayer = N'Cleanse';

--.........................................................................
--Register load objects
--.........................................................................

EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Branch',                               @ModelObjectPart = N'Entity Cleanse Action',                @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Cleanse',                              @ModelObjectType = N'Entity',                               @LoadObject = N'CLS_EN_Branch_Action',                 @SchemaName = N'{dimensionalmssql#cleanse#schema_name}', @DatabaseName = N'{dimensionalmssql#cleanse#database_name}', @ServerName = N'{dimensionalmssql#cleanse#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2020, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Branch',                               @ModelObjectPart = N'Entity Cleanse Loader',                @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Cleanse',                              @ModelObjectType = N'Entity',                               @LoadObject = N'CLS_EN_Branch_Loader',                 @SchemaName = N'{dimensionalmssql#cleanse#schema_name}', @DatabaseName = N'{dimensionalmssql#cleanse#database_name}', @ServerName = N'{dimensionalmssql#cleanse#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2010, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Customer',                             @ModelObjectPart = N'Entity Cleanse Action',                @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Cleanse',                              @ModelObjectType = N'Entity',                               @LoadObject = N'CLS_EN_Customer_Action',               @SchemaName = N'{dimensionalmssql#cleanse#schema_name}', @DatabaseName = N'{dimensionalmssql#cleanse#database_name}', @ServerName = N'{dimensionalmssql#cleanse#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2020, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Customer',                             @ModelObjectPart = N'Entity Cleanse Loader',                @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Cleanse',                              @ModelObjectType = N'Entity',                               @LoadObject = N'CLS_EN_Customer_Loader',               @SchemaName = N'{dimensionalmssql#cleanse#schema_name}', @DatabaseName = N'{dimensionalmssql#cleanse#database_name}', @ServerName = N'{dimensionalmssql#cleanse#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2010, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Item',                                 @ModelObjectPart = N'Entity Cleanse Action',                @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Cleanse',                              @ModelObjectType = N'Entity',                               @LoadObject = N'CLS_EN_Item_Action',                   @SchemaName = N'{dimensionalmssql#cleanse#schema_name}', @DatabaseName = N'{dimensionalmssql#cleanse#database_name}', @ServerName = N'{dimensionalmssql#cleanse#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2020, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Item',                                 @ModelObjectPart = N'Entity Cleanse Loader',                @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Cleanse',                              @ModelObjectType = N'Entity',                               @LoadObject = N'CLS_EN_Item_Loader',                   @SchemaName = N'{dimensionalmssql#cleanse#schema_name}', @DatabaseName = N'{dimensionalmssql#cleanse#database_name}', @ServerName = N'{dimensionalmssql#cleanse#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2010, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'ItemUnitOfMeasure',                    @ModelObjectPart = N'Entity Cleanse Action',                @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Cleanse',                              @ModelObjectType = N'Entity',                               @LoadObject = N'CLS_EN_ItemUnitOfMeasure_Action',      @SchemaName = N'{dimensionalmssql#cleanse#schema_name}', @DatabaseName = N'{dimensionalmssql#cleanse#database_name}', @ServerName = N'{dimensionalmssql#cleanse#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2070, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'ItemUnitOfMeasure',                    @ModelObjectPart = N'Entity Cleanse Loader',                @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Cleanse',                              @ModelObjectType = N'Entity',                               @LoadObject = N'CLS_EN_ItemUnitOfMeasure_Loader',      @SchemaName = N'{dimensionalmssql#cleanse#schema_name}', @DatabaseName = N'{dimensionalmssql#cleanse#database_name}', @ServerName = N'{dimensionalmssql#cleanse#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2060, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Loyaltycard',                          @ModelObjectPart = N'Entity Cleanse Action',                @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Cleanse',                              @ModelObjectType = N'Entity',                               @LoadObject = N'CLS_EN_Loyaltycard_Action',            @SchemaName = N'{dimensionalmssql#cleanse#schema_name}', @DatabaseName = N'{dimensionalmssql#cleanse#database_name}', @ServerName = N'{dimensionalmssql#cleanse#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2070, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Loyaltycard',                          @ModelObjectPart = N'Entity Cleanse Loader',                @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Cleanse',                              @ModelObjectType = N'Entity',                               @LoadObject = N'CLS_EN_Loyaltycard_Loader',            @SchemaName = N'{dimensionalmssql#cleanse#schema_name}', @DatabaseName = N'{dimensionalmssql#cleanse#database_name}', @ServerName = N'{dimensionalmssql#cleanse#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2060, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'POS',                                  @ModelObjectPart = N'Entity Cleanse Action',                @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Cleanse',                              @ModelObjectType = N'Entity',                               @LoadObject = N'CLS_EN_POS_Action',                    @SchemaName = N'{dimensionalmssql#cleanse#schema_name}', @DatabaseName = N'{dimensionalmssql#cleanse#database_name}', @ServerName = N'{dimensionalmssql#cleanse#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2070, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'POS',                                  @ModelObjectPart = N'Entity Cleanse Loader',                @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Cleanse',                              @ModelObjectType = N'Entity',                               @LoadObject = N'CLS_EN_POS_Loader',                    @SchemaName = N'{dimensionalmssql#cleanse#schema_name}', @DatabaseName = N'{dimensionalmssql#cleanse#database_name}', @ServerName = N'{dimensionalmssql#cleanse#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2060, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Cleanse Action',                  @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Cleanse',                              @ModelObjectType = N'Fact',                                 @LoadObject = N'CLS_F_Salestransaction_Action',        @SchemaName = N'{dimensionalmssql#cleanse#schema_name}', @DatabaseName = N'{dimensionalmssql#cleanse#database_name}', @ServerName = N'{dimensionalmssql#cleanse#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2120, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Cleanse Loader',                  @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Cleanse',                              @ModelObjectType = N'Fact',                                 @LoadObject = N'CLS_F_Salestransaction_Loader',        @SchemaName = N'{dimensionalmssql#cleanse#schema_name}', @DatabaseName = N'{dimensionalmssql#cleanse#database_name}', @ServerName = N'{dimensionalmssql#cleanse#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 2110, @ExecutionPriority = 0, @IsActive = 1;

--.........................................................................
--Register load object dependencies
--.........................................................................

EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Branch',                               @ModelObjectPart = N'Entity Cleanse Action',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Branch',                               @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Branch',                               @ModelObjectPart = N'Entity Cleanse Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Branch',                               @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Customer',                             @ModelObjectPart = N'Entity Cleanse Action',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Customer',                             @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Customer',                             @ModelObjectPart = N'Entity Cleanse Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Customer',                             @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Item',                                 @ModelObjectPart = N'Entity Cleanse Action',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Item',                                 @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Item',                                 @ModelObjectPart = N'Entity Cleanse Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Item',                                 @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'ItemUnitOfMeasure',                    @ModelObjectPart = N'Entity Cleanse Action',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'ItemUnitOfMeasure',                    @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'ItemUnitOfMeasure',                    @ModelObjectPart = N'Entity Cleanse Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Item',                                 @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'ItemUnitOfMeasure',                    @ModelObjectPart = N'Entity Cleanse Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Item',                                 @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'ItemUnitOfMeasure',                    @ModelObjectPart = N'Entity Cleanse Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'ItemUnitOfMeasure',                    @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Loyaltycard',                          @ModelObjectPart = N'Entity Cleanse Action',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Loyaltycard',                          @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Loyaltycard',                          @ModelObjectPart = N'Entity Cleanse Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Customer',                             @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Loyaltycard',                          @ModelObjectPart = N'Entity Cleanse Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Customer',                             @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Loyaltycard',                          @ModelObjectPart = N'Entity Cleanse Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Loyaltycard',                          @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'POS',                                  @ModelObjectPart = N'Entity Cleanse Action',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'POS',                                  @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'POS',                                  @ModelObjectPart = N'Entity Cleanse Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Branch',                               @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'POS',                                  @ModelObjectPart = N'Entity Cleanse Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Branch',                               @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'POS',                                  @ModelObjectPart = N'Entity Cleanse Loader',                @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'POS',                                  @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Cleanse Action',                  @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Salestransaction',                     @DependentOnModelObjectPart = N'Fact Cleanse Loader',                  @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Cleanse Loader',                  @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Branch',                               @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Cleanse Loader',                  @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Branch',                               @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Cleanse Loader',                  @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Customer',                             @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Cleanse Loader',                  @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Customer',                             @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Cleanse Loader',                  @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Item',                                 @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Cleanse Loader',                  @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Item',                                 @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Cleanse Loader',                  @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'ItemUnitOfMeasure',                    @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Cleanse Loader',                  @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'ItemUnitOfMeasure',                    @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Cleanse Loader',                  @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'ItemUnitOfMeasure',                    @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Cleanse Loader',                  @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Loyaltycard',                          @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Cleanse Loader',                  @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Loyaltycard',                          @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Cleanse Loader',                  @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Loyaltycard',                          @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Cleanse Loader',                  @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'POS',                                  @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Cleanse Loader',                  @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'POS',                                  @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Cleanse Loader',                  @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'POS',                                  @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Cleanse Loader',                  @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Salestransaction',                     @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;

GO
