--.........................................................................
--SQL script for post deployment configuration of load control
--Project: Dimensional MSSQL
--Layer: Core
--.........................................................................
USE [{loadcontrol#loadcontrol#database_name}];
GO


--.........................................................................
--Prepare registration of load objects
--.........................................................................

EXEC [{loadcontrol#loadcontrol#schema_name}].[Build_LoadConfig] @LoadConfig = N'Dimensional MSSQL', @ModelObjectLayer = N'Core';

--.........................................................................
--Register load objects
--.........................................................................

EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Branch',                               @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Core',                                 @ModelObjectType = N'Entity',                               @LoadObject = N'COR_EN_Branch_Loader',                 @SchemaName = N'{dimensionalmssql#core#schema_name}', @DatabaseName = N'{dimensionalmssql#core#database_name}', @ServerName = N'{dimensionalmssql#core#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 3020, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Customer',                             @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Core',                                 @ModelObjectType = N'Entity',                               @LoadObject = N'COR_EN_Customer_Loader',               @SchemaName = N'{dimensionalmssql#core#schema_name}', @DatabaseName = N'{dimensionalmssql#core#database_name}', @ServerName = N'{dimensionalmssql#core#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 3020, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Item',                                 @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Core',                                 @ModelObjectType = N'Entity',                               @LoadObject = N'COR_EN_Item_Loader',                   @SchemaName = N'{dimensionalmssql#core#schema_name}', @DatabaseName = N'{dimensionalmssql#core#database_name}', @ServerName = N'{dimensionalmssql#core#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 3020, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'ItemUnitOfMeasure',                    @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Core',                                 @ModelObjectType = N'Entity',                               @LoadObject = N'COR_EN_ItemUnitOfMeasure_Loader',      @SchemaName = N'{dimensionalmssql#core#schema_name}', @DatabaseName = N'{dimensionalmssql#core#database_name}', @ServerName = N'{dimensionalmssql#core#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 3070, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Loyaltycard',                          @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Core',                                 @ModelObjectType = N'Entity',                               @LoadObject = N'COR_EN_Loyaltycard_Loader',            @SchemaName = N'{dimensionalmssql#core#schema_name}', @DatabaseName = N'{dimensionalmssql#core#database_name}', @ServerName = N'{dimensionalmssql#core#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 3070, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'POS',                                  @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Core',                                 @ModelObjectType = N'Entity',                               @LoadObject = N'COR_EN_POS_Loader',                    @SchemaName = N'{dimensionalmssql#core#schema_name}', @DatabaseName = N'{dimensionalmssql#core#database_name}', @ServerName = N'{dimensionalmssql#core#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 3070, @ExecutionPriority = 0, @IsActive = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @ModelObjectLayer = N'Core',                                 @ModelObjectType = N'Fact',                                 @LoadObject = N'COR_F_Salestransaction_Loader',        @SchemaName = N'{dimensionalmssql#core#schema_name}', @DatabaseName = N'{dimensionalmssql#core#database_name}', @ServerName = N'{dimensionalmssql#core#server_name}', @ErrorBehavior = N'Default', @ExecutionTechnology = N'SQL', @ExecutionSortOrder = 3110, @ExecutionPriority = 0, @IsActive = 1;

--.........................................................................
--Register load object dependencies
--.........................................................................

EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Branch',                               @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Branch',                               @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Branch',                               @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Branch',                               @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Customer',                             @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Customer',                             @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Customer',                             @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Customer',                             @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Item',                                 @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Item',                                 @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Item',                                 @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Item',                                 @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'ItemUnitOfMeasure',                    @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Item',                                 @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'ItemUnitOfMeasure',                    @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Item',                                 @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'ItemUnitOfMeasure',                    @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Item',                                 @DependentOnModelObjectPart = N'Entity Core Loader',                   @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'ItemUnitOfMeasure',                    @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'ItemUnitOfMeasure',                    @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'ItemUnitOfMeasure',                    @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'ItemUnitOfMeasure',                    @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'ItemUnitOfMeasure',                    @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'ItemUnitOfMeasure',                    @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Loyaltycard',                          @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Customer',                             @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Loyaltycard',                          @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Customer',                             @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Loyaltycard',                          @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Customer',                             @DependentOnModelObjectPart = N'Entity Core Loader',                   @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Loyaltycard',                          @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Loyaltycard',                          @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Loyaltycard',                          @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Loyaltycard',                          @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Loyaltycard',                          @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Loyaltycard',                          @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'POS',                                  @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Branch',                               @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'POS',                                  @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Branch',                               @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'POS',                                  @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Branch',                               @DependentOnModelObjectPart = N'Entity Core Loader',                   @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'POS',                                  @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'POS',                                  @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'POS',                                  @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'POS',                                  @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'POS',                                  @ModelObjectPart = N'Entity Core Loader',                   @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'POS',                                  @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Branch',                               @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Branch',                               @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Branch',                               @DependentOnModelObjectPart = N'Entity Core Loader',                   @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Customer',                             @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Customer',                             @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Customer',                             @DependentOnModelObjectPart = N'Entity Core Loader',                   @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Item',                                 @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Item',                                 @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Item',                                 @DependentOnModelObjectPart = N'Entity Core Loader',                   @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'ItemUnitOfMeasure',                    @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'ItemUnitOfMeasure',                    @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'ItemUnitOfMeasure',                    @DependentOnModelObjectPart = N'Entity Core Loader',                   @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'ItemUnitOfMeasure',                    @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Loyaltycard',                          @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Loyaltycard',                          @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Loyaltycard',                          @DependentOnModelObjectPart = N'Entity Core Loader',                   @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Loyaltycard',                          @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'POS',                                  @DependentOnModelObjectPart = N'Entity Cleanse Action',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'POS',                                  @DependentOnModelObjectPart = N'Entity Cleanse Loader',                @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'POS',                                  @DependentOnModelObjectPart = N'Entity Core Loader',                   @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'POS',                                  @DependentOnModelObjectPart = N'Stage Loader',                         @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Salestransaction',                     @DependentOnModelObjectPart = N'Fact Cleanse Action',                  @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;
EXEC [{loadcontrol#loadcontrol#schema_name}].[AddOrUpdate_LoadConfig_LoadObject_Dependency] @LoadConfig = N'Dimensional MSSQL',                    @ModelObject = N'Salestransaction',                     @ModelObjectPart = N'Fact Core TruncateInsertLoader',       @ModelObjectDataflow = N'Dataflow1',                            @DependentOnLoadConfig = N'Dimensional MSSQL',                    @DependentOnModelObject = N'Salestransaction',                     @DependentOnModelObjectPart = N'Fact Cleanse Loader',                  @DependentOnModelObjectDataflow = N'Dataflow1',                            @AllowDisable = 1;

GO
